"""Initial migration

Revision ID: c61209002771
Revises: 
Create Date: 2025-11-24 21:48:05.900051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61209002771'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_menu_items_category', table_name='menu_items')
    op.drop_index('ix_menu_items_is_available', table_name='menu_items')
    op.drop_index('ix_menu_items_is_featured', table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_index('ix_users_username', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_order_items_menu_item_id', table_name='order_items')
    op.drop_index('ix_order_items_order_id', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_orders_order_date', table_name='orders')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_user_id', table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('order_number', sa.VARCHAR(length=20), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('customer_name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('customer_email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('customer_phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('subtotal', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('tax', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('total', sa.NUMERIC(precision=10, scale=2), nullable=True),
    sa.Column('payment_status', sa.VARCHAR(length=20), nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(length=100), nullable=True),
    sa.Column('order_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('table_number', sa.INTEGER(), nullable=True),
    sa.Column('order_date', sa.DATETIME(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('prepared_at', sa.DATETIME(), nullable=True),
    sa.Column('ready_at', sa.DATETIME(), nullable=True),
    sa.Column('completed_at', sa.DATETIME(), nullable=True),
    sa.Column('cancelled_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint("order_type IN ('dine_in', 'takeout', 'delivery')", name='check_order_type'),
    sa.CheckConstraint("payment_status IN ('unpaid', 'paid', 'refunded', 'partially_refunded', 'failed')", name='check_payment_status'),
    sa.CheckConstraint("status IN ('pending', 'confirmed', 'preparing', 'ready', 'completed', 'cancelled')", name='check_order_status'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_orders_user_id', 'orders', ['user_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_index('ix_orders_order_date', 'orders', ['order_date'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('menu_item_id', sa.INTEGER(), nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('item_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('quantity', sa.INTEGER(), nullable=False),
    sa.Column('special_instructions', sa.TEXT(), nullable=True),
    sa.Column('total_price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('item_price >= 0', name='check_item_price_positive'),
    sa.CheckConstraint('quantity > 0', name='check_quantity_positive'),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_items_order_id', 'order_items', ['order_id'], unique=False)
    op.create_index('ix_order_items_menu_item_id', 'order_items', ['menu_item_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=64), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('is_admin', sa.BOOLEAN(), nullable=True),
    sa.Column('email_verified', sa.BOOLEAN(), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=20), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('profile_image', sa.VARCHAR(length=255), nullable=True),
    sa.Column('last_login_at', sa.DATETIME(), nullable=True),
    sa.Column('last_seen', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_table('menu_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('price', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_available', sa.BOOLEAN(), nullable=True),
    sa.Column('is_featured', sa.BOOLEAN(), nullable=True),
    sa.Column('calories', sa.INTEGER(), nullable=True),
    sa.Column('is_vegetarian', sa.BOOLEAN(), nullable=True),
    sa.Column('is_vegan', sa.BOOLEAN(), nullable=True),
    sa.Column('is_gluten_free', sa.BOOLEAN(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('display_order', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('price >= 0', name='check_price_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_menu_items_is_featured', 'menu_items', ['is_featured'], unique=False)
    op.create_index('ix_menu_items_is_available', 'menu_items', ['is_available'], unique=False)
    op.create_index('ix_menu_items_category', 'menu_items', ['category'], unique=False)
    # ### end Alembic commands ###
